spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?characterEncoding=utf8&serverTimezone=UTC&nullCatalogMeansCurrent=true&useSSL=false
    username: root
    password: root
  jpa:
    generate-ddl: false # 自动生成数据库表
    show-sql: true
    hibernate:
      ddl-auto: none
    database: mysql
  activiti:
    database-schema-update: false # 自动生成数据库表
    check-process-definitions: false
    serialize-p-o-j-os-in-variables-to-json: true
    db-history-used: true
    history-level: audit
mybatis:
  type-aliases-package: com.fk.**.model
  mapper-locations: classpath*:mapper/*Mapper.xml
upload:
    path: /upload